routes/clan_routes.py
from flask import Blueprint, render_template, request, current_app, flash
import urllib.parse
import copy
import json
import traceback
from utils.helper import get_level_badge_class

clan_bp = Blueprint('clan_bp', __name__)

@clan_bp.route('/clan')
def clan():
    current_app.app_logger.info("Received clan info request")
    ClanTagList = current_app.cocinfo_cocparm['cocinfo_clan_list']

    cocdata = []
    for ClanTag in ClanTagList:
        try:
            data = current_app.coc_api_client.get_cwl_list(ClanTag)
            if data:
                cocdata.append(data)
            else:
                current_app.app_logger.warning(f"No data returned for ClanTag: {ClanTag}")
        except Exception as e:
            current_app.app_logger.error(f"Error fetching CWL list for {ClanTag}: {e}")
            flash(f"Failed to load data for clan {ClanTag}. Please try again later.", "error")
    return render_template('clan.html', ThisHTML="clan", ClanData=cocdata, 
                           cocparm=current_app.cocinfo_cocparm)

@clan_bp.route('/clan/<string:clan_tag>/info')
def get_clan_details(clan_tag:None):
    # get_clan_details replace claninfo
    data = current_app.coc_api_client.get_clan_details(clan_tag)
    return render_template('claninfo.html', ClanNameTag=clan_tag, ClanData=data, ThisHTML="clan",
                           cocparm=current_app.cocinfo_cocparm,)


@clan_bp.route('/clan/<clan_tag>/supertroops', methods=['GET'])
def supertroops(clan_tag):
    data = current_app.coc_api_client.get_clan_supertroops(clan_tag)
    return render_template('supertroops.html', ThisHTML='supertroops', ClanData=data,
                           cocparm=current_app.cocinfo_cocparm,)


@clan_bp.route('/clan/<clan_tag>/troops', methods=['GET'])
def display_clan_troops(clan_tag):
    clan_data = None # Initialize
    try:
        clan_data = current_app.coc_api_client.get_clan_troops(clan_tag) 
        if clan_data and 'error' in clan_data:
            flash(f"Error fetching clan troops data: {clan_data['error']}", 'danger')
            clan_data = None
        elif not clan_data:
            flash(f"Could not retrieve clan troops data for tag: {clan_tag}.", 'warning')
    except Exception as e:
        current_app.logger.error(f"Error calling clan troops API for {clan_tag}: {e}")
        flash("An unexpected error occurred while fetching clan troops data. Please try again later.", 'danger')
        clan_data = None

    return render_template(
        'clantroops.html',
        ClanNameTag=clan_tag,
        ClanData=clan_data,
        ThisHTML="clan",
        get_level_badge_class=get_level_badge_class,
        cocparm=current_app.cocinfo_cocparm
    )

@clan_bp.route('/clan/<clan_tag>/progress', methods=['GET'])    
def display_clan_progress(clan_tag):
    achievement = request.args.get('achievement')
    if achievement:
        achievement = achievement.split(':', 1)[0].strip()

    try:
        clan_data = current_app.coc_api_client.get_clan_progress(clan_tag, achievement) 
        if clan_data and 'error' in clan_data:
            flash(f"Error fetching clan troops data: {clan_data['error']}", 'danger')
            clan_data = None
        elif not clan_data:
            flash(f"Could not retrieve clan troops data for tag: {clan_tag}.", 'warning')
    except Exception as e:
        current_app.logger.error(f"Error calling clan troops API for {clan_tag}: {e}")
        flash("An unexpected error occurred while fetching clan troops data. Please try again later.", 'danger')
        clan_data = None
    return render_template('clanprogress.html', ThitHTML='clanprogress', ClanData=clan_data,
                           cocparm=current_app.cocinfo_cocparm)


@clan_bp.route('/clan/currentwar/<clan_tag>', methods=['GET'])
def display_currentwar(clan_tag: str):
    war_data = None
    clan_war_team = None
    try:
        war_data = current_app.coc_api_client.get_current_war(clan_tag)
        if war_data and 'error' in war_data:
            flash(f"Error fetching current war data: {war_data['error']}", 'danger')
            war_data = None
        elif not war_data:
            flash(f"Could not retrieve current war data for tag: {clan_tag}.", 'warning')
        else:
            clan_war_team = {
                    'clan': {},
                    'opponent': {},
                    'player': {},
                    'order': {}
                }
            if war_data['state'] != 'notInWar':
                for group in ['clan', 'opponent']:
                    for member in war_data[group]['members']:
                        clan_war_team[group][member['mapPosition']] = copy.deepcopy(member)
                        clan_war_team['player'][member['tag']] = copy.deepcopy(member)
                        if 'attacks' in member:
                            for attack in member['attacks']:
                                if 'order' in attack:
                                    clan_war_team['order'][attack['order']] = copy.deepcopy(attack)
                                    clan_war_team['order'][attack['order']]['team'] = group
                clan_war_team['orderSeq'] = sorted(clan_war_team['order'].keys())
    except Exception as e:
        error_msg = f"Error calling current war API for {clan_tag}: {e}\n"
        error_msg += f"{traceback.format_exc()}"
        current_app.logger.error(error_msg)
        flash("An unexpected error occcurred while fetching current war data. Please try again later.", 'danger')
        war_data = None
    
    dumpdata = json.dumps(clan_war_team, indent=4).replace("\n", "<br>")    
    return render_template('currentwar.html', ThisHTML="currentwar", ClanWar=war_data, 
                           ClanWarTeam=clan_war_team, dumpdata=dumpdata, 
                           cocparm=current_app.cocinfo_cocparm)

@clan_bp.route('/clan/warlog/<clan_tag>', methods=['GET'])
def display_war_log(clan_tag: str):
    war_log_data = current_app.coc_api_client.get_clan_war_log(clan_tag)
    if war_log_data and 'error' in war_log_data:
        flash(f"Error fetching war log data: {war_log_data['error']}", 'danger')
        war_log_data = None
    elif not war_log_data:
        flash(f"No war log data for tag: {clan_tag}.", 'warning')
    else:
        war_log_data['clan'] = {}
        war_log_data['player'] = {}
        for war_log in war_log_data['print']:
            war_log_endTime = war_log['endTime'][:8]
            if war_log_data['warlog'][war_log_endTime]['state'] != 'noData':
                for member in war_log_data['warlog'][war_log_endTime]['clan']['members']:
                    if member['tag'] not in war_log_data['clan']:
                        war_log_data['clan'][member['tag']] = copy.deepcopy(member)
                        war_log_data['player'][member['tag']] = copy.deepcopy(member)
                        war_log_data['clan'][member['tag']]['mapPositionSum'] = member['mapPosition']
                        war_log_data['clan'][member['tag']]['mapPositionCount'] = 1
                    else:
                        war_log_data['clan'][member['tag']]['mapPositionSum'] += member['mapPosition']
                        war_log_data['clan'][member['tag']]['mapPositionCount'] += 1
                    if 'attacks' in member:
                        war_log_data['clan'][member['tag']][war_log_endTime + '-1'] = copy.deepcopy(member['attacks'][0])
                        if len(member['attacks']) > 1:
                            war_log_data['clan'][member['tag']][war_log_endTime + '-2'] = copy.deepcopy(member['attacks'][1])
                        else:
                            war_log_data['clan'][member['tag']][war_log_endTime + '-2'] = {}
                    else:
                        war_log_data['clan'][member['tag']][war_log_endTime + '-1'] = {}
                        war_log_data['clan'][member['tag']][war_log_endTime + '-2'] = {}
                for member in war_log_data['warlog'][war_log_endTime]['opponent']['members']:
                    war_log_data['player'][member['tag']] = copy.deepcopy(member)
        war_log_data['mapPositionSeq'] = {}
        for membertag in war_log_data['clan']:
            war_log_data['clan'][membertag]['mapPositionAvg'] = \
                war_log_data['clan'][membertag]['mapPositionSum'] / war_log_data['clan'][membertag]['mapPositionCount']
            war_log_data['mapPositionSeq']["{:04.1f}".format(war_log_data['clan'][membertag]['mapPositionAvg']) + membertag] = membertag
        war_log_data['mapPositionSeq'] = dict(sorted(war_log_data['mapPositionSeq'].items()))
        # fetch other member data into summary table
        clan_data = current_app.coc_api_client.get_clan_details(clan_tag)
        for member in clan_data['memberList']:
            if member['tag'] not in war_log_data['clan']:
                war_log_data['mapPositionSeq']['99.9' + member['tag']] = member['tag']
                war_log_data['clan'][member['tag']] = {'mapPositionAvg' : 99.9}
                war_log_data['clan'][member['tag']]['townhallLevel'] = member['townHallLevel']
                war_log_data['clan'][member['tag']]['name'] = member['name']
    dumpdata = json.dumps(war_log_data, indent=4).replace("\n", "<br>").replace(" ", "&nbsp;")   
    return render_template('clanwarlog.html', ThisHTML="clanwarlog", ClanWarLog=war_log_data, 
                           cocparm=current_app.cocinfo_cocparm,
                           dumpdata=dumpdata)




@clan_bp.route('/wardetail/<clan_tag>/<war_date>', methods=['GET'])
def display_wardetail(clan_tag: str, war_date: str):
    clan_war_team = {
            'clan': {},
            'opponent': {},
            'player': {},
            'order': {}
        }

    war_data = current_app.coc_api_client.get_war_detail(clan_tag, war_date)
    if war_data and war_data['state'] != 'noData':
        for group in ['clan', 'opponent']:
            for member in war_data[group]['members']:

routes/cwl_routes.py
# ./routes/cwl_routes.py
from flask import Blueprint, render_template, request, current_app, flash
import urllib.parse
import json
import copy
from utils.helper import get_level_badge_class

cwl_bp = Blueprint('cwl_bp', __name__)

@cwl_bp.route('/cwlinfo/<clan_tag>', defaults={'season': None}, methods=['GET'])
@cwl_bp.route('/cwlinfo/<clan_tag>/<season>', methods=['GET'])
def display_cwl_info(clan_tag, season:None):
    cwl_data = None
    try:
        cwl_data = current_app.coc_api_client.get_cwl_info(clan_tag, season)
        if cwl_data and 'error' in cwl_data:
            flash(f"Error fetching cwl data: {cwl_data['error']}", 'danger')
            cwl_data = None
        elif not cwl_data:
            flash(f"Could not retrieve cwl data for clan: {clan_tag}.", 'warning')
    except Exception as e:
        current_app.logger.error(f"Error calling cwl info API for {clan_tag}: {e}")
        flash("An unexpected error occurred while fetching cwl data. Please try again later.", 'danger')
        cwl_data = None
    if cwl_data:
        for clan in cwl_data['clans']:
            consolidated_data = {}
            consolidated_member_count = {}
            for member in clan['members']:
                level = member['townHallLevel']
                if level not in consolidated_data:
                    consolidated_data[level] = []
                    consolidated_member_count[level] = 0
                consolidated_data[level].append(member)
                consolidated_member_count[level] = consolidated_member_count[level] + 1
            clan['consolidated_member'] = {k: v for k, v in sorted(consolidated_data.items(), key=lambda item:item[0], reverse=True)}
            clan['consolidated_member_count'] = consolidated_member_count
        round = 1
        for round_detail in cwl_data['rounds']:
            round_detail['day'] = round
            round = round + 1
    return render_template('clanwarleague.html', ThisHTML="clanwarleague", ClanWar=cwl_data,
                           cocparm=current_app.cocinfo_cocparm)



@cwl_bp.route('/wartag/<clan_tag>/<season>/<round_day>', methods=['GET'])
def wartag(clan_tag, season, round_day):
    cwl_data = current_app.coc_api_client.get_cwl_info(clan_tag, season)
    if cwl_data and 'error' in cwl_data:
        flash(f"Error fetching cwl data: {cwl_data['error']}", 'danger')
        cwl_data = None
    elif not cwl_data:
        flash(f"Could not retrieve cwl data for clan: {clan_tag}.", 'warning')

    round_index = int(round_day) - 1
    total_member_list = {}
    dumpdata = None
    if cwl_data:
        if 'rounds' in cwl_data and len(cwl_data['rounds']) > round_index:
            target_round_data = cwl_data['rounds'][round_index]
            for war_tag in target_round_data.get('warTags', []):
                if war_tag == '#0':
                    target_round_data[war_tag] = None
                    continue
                target_round_data[war_tag] = current_app.coc_api_client.get_war_tag_detail(war_tag[1:], season)
                # sort clan member in mapPosition order
                if (target_round_data[war_tag].get('clan') and 
                    target_round_data[war_tag]['clan'].get('members')):
                    members_list = target_round_data[war_tag]['clan']['members']
                    for member in members_list:
                        total_member_list[member['tag']] = member
                    members_list.sort(key=lambda member_dict: int(member_dict['mapPosition']))
                # sort oppopent member in mapPosition order
                if (target_round_data[war_tag].get('opponent') and 
                    target_round_data[war_tag]['opponent'].get('members')):
                    members_list = target_round_data[war_tag]['opponent']['members']
                    for member in members_list:
                        total_member_list[member['tag']] = member
                    members_list.sort(key=lambda member_dict: int(member_dict['mapPosition']))

                war_tag_data = cwl_data['rounds'][round_index][war_tag]
                if (war_tag_data['clan']['stars'] > war_tag_data['opponent']['stars'] or
                    (war_tag_data['clan']['stars'] == war_tag_data['opponent']['stars'] and 
                     war_tag_data['clan']['destructionPercentage'] > war_tag_data['opponent']['destructionPercentage'])):
                    war_tag_data['result'] = 'win'
                else:
                    war_tag_data['result'] = 'lost'
        dumpdata = json.dumps(cwl_data, indent=4).replace("\n", "<br>").replace(" ", "&nbsp;")   
    return render_template('wartag.html', ThisHTML='clanwarleague', ClanWar=cwl_data, RoundDay=round_index, 
                           totalMemberList=total_member_list, dumpdata=dumpdata,
                           cocparm=current_app.cocinfo_cocparm)

@cwl_bp.route('/cwlsummary/<clan_tag>/<season>', methods=['GET'])
def cwlsummary(clan_tag: str, season: str):
    
    cwl_summary_data = current_app.coc_api_client.get_cwl_summary(clan_tag, season)
    if 'rounds' in cwl_summary_data:
        clanlist = cwl_summary_data['clanlist']
        clansummary = cwl_summary_data['clansummary']
        dumpdata = json.dumps(clanlist, indent=4).replace("\n", "<br>").replace(" ", "&nbsp;")    
        return render_template('cwlteam.html', ThisHTML="clanwarleague", ClanWar=cwl_summary_data, 
                               clanlist=clanlist, clansummary=clansummary, dumpdata=dumpdata,
                               cocparm=current_app.cocinfo_cocparm)
    else:
        flash(f"Error fetching CWL summary for clan {clan_tag}, season {season}: {cwl_summary_data.get('error', 'Unknown error')}", 'danger')
        return render_template('cwlteam.html', ThisHTML="clanwarleague", ClanWar=None, clanlist=None, 
                               clansummary=None, 
                               cocparm=current_app.cocinfo_cocparm)

templates/clanwarlog.html
{% extends 'base.html' %}

{% block header %}
  {% if ClanWarLog and ClanWarLog['items'] %}
    {% set main_clan = ClanWarLog['items'][0]['clan'] %}
    {% set formatted_clantag = main_clan['tag'][1:] %}

    <div class="d-flex align-items-center mb-3">
      <a href="{{ url_for('clan_bp.get_clan_details', clan_tag=formatted_clantag) }}" class="text-decoration-none d-flex align-items-center">
        <img src="{{ main_clan['badgeUrls']['small'] }}" alt="{{ main_clan['name'] }} badge"
             class="me-3" style="max-height: 60px">
        <h1>{% block title %}{{ ClanWarLog['items'][0]['clan']['name'] }} War Log{% endblock %}</h1></a>
    </div>

    <div class="d-flex flex-wrap gap-2 mb-3">
      <a href="{{ url_for('clan_bp.display_currentwar', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Clan War</a>
      <a href="{{ url_for('clan_bp.display_war_log', clan_tag=formatted_clantag) }}" class="btn btn-primary btn-sm active" aria-current="page">War Log</a>
      <a href="{{ url_for('clan_bp.display_clan_progress', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Clan Progress</a>
      <a href="{{ url_for('clan_bp.supertroops', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Super Troops</a>
      <a href="{{ url_for('cwl_bp.display_cwl_info', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">CWL (local)</a>
      <a href="{{ url_for('clan_bp.display_clan_troops', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Troops</a>

      <a href="https://www.clashofstats.com/clans/{{ formatted_clantag }}/history/past-members" class="btn btn-outline-info btn-sm"
        target="_blank" rel="noopener noreferrer">Past Members<i class="bi bi-box-arrow-up-right ms-1"></i></a>
    </div>
  {% else %}
    <div class="alert alert-info text-center" role="alert">
      Clan War Log data is unavailable.
    </div>

  {% endif %}
{% endblock %}

{% block content %}
  {% if ClanWarLog and ClanWarLog['items'] %}
    {% set main_clan = ClanWarLog['items'][0]['clan'] %}
    {% set formatted_clantag = main_clan['tag'][1:] %}


    {##########################}
    {# Clan War Summary Table #}
    {##########################}
    <div class="table-responsive mb-4">
      <table class="table table-bordered table-striped table-hover war-log-table text-center align-middle">
        <thead>
          <tr>
            <th><span>End Time</span>
                <span><small>(UTC+0)</small></span></th>
            <th>Size</th>
            <th>Our Result</th>
            <th>Opponent</th>
            <th>Their Result</th>
          </tr>
        </thead>
        <tbody>
          {% for ClanWar in ClanWarLog['print'] %}
            {% if ClanWar['opponent'] %}
              <tr class="{% if ClanWar['result'] == 'win' %}table-success{% elif ClanWar['result'] == "lose" %}table-danger{% endif %}">
                <td>
                  <a href="{{ url_for('clan_bp.display_wardetail', clan_tag=formatted_clantag, war_date=ClanWar['endTime'][:8]) }}" class="text-decoration-none text-body">
                    <span>{{ ClanWar['endTime'][6:8] }}/{{ ClanWar['endTime'][4:6] }}</span>
                    <span>{{ ClanWar['endTime'][9:11] }}:{{ ClanWar['endTime'][11:13] }}</span>
                  </a>
                </td>
                <td>{{ ClanWar['teamSize'] }}</td>
                <td>
                  {{ ClanWar['clan']['stars'] }}<i class="bi bi-star-fill text-warning"></i>
                  &nbsp;/&nbsp;{{ "%.1f"|format(ClanWar['clan']['destructionPercentage']) }}%
                </td>
                <td>
                  <img height=25px width=25px src="{{ ClanWar['opponent']['badgeUrls']['small'] }}" alt="{{ ClanWar['opponent']['name'] }} badge" class="me-2">
                  {{ ClanWar['opponent']['name'] }}
                </td>
                <td>
                  {{ ClanWar['opponent']['stars'] }}<i class="bi bi-star-fill text-warning"></i>
                  &nbsp;/&nbsp;{{ "%.1f"|format(ClanWar['opponent']['destructionPercentage']) }}%
                </td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>

    {#############################################}
    {# Clan Member Performance Across Wars Table #}
    {#############################################}
    <h3 class="h5 mb-3 mt-4">Clan Member Attack Performance Log</h3>
    <div class="table-responsive table-scroll-container">
      <table class="table table-bordered table-striped table-hover text-center align-middle player-progress-table">
        <thead>
          <tr>
            <th></th>
            {% for ClanWar in ClanWarLog['print'] %}
              <th colspan="2">
                {{ ClanWar['endTime'][6:8] }}/{{ ClanWar['endTime'][4:6] }}/{{ ClanWar['endTime'][:4] }}<br/>
                <small>{{ ClanWar['endTime'][9:11] }}:{{ ClanWar['endTime'][11:13] }}</small><br/>
                <span class="badge bg-secondary">{{ ClanWarLog['warlog'][ClanWar['endTime'][:8]]['state'] }}</span>
              </th>
            {% endfor %}
          </tr>
          <tr>
            <th class="sticky-header sticky-column-left sticky-corner">Member</th>
            {% for ClanWar in ClanWarLog['print'] %}
            <th class="sticky-header">attack 1</th>
            <th class="sticky-header">attack 2</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for tag, membertag in ClanWarLog['mapPositionSeq'].items() %}
          {% set member_data = ClanWarLog['clan'][membertag] %}
          <tr>
            <td class="text-start text-nowrap sticky-column-left">
              {{ "%.1f"|format(member_data['mapPositionAvg']) }}<br/>
              <img src="{{ url_for('static', filename='1_' + member_data['townhallLevel']|string + '.png') }}"
                   alt="TH{{ member_data['townhallLevel'] }}" class="me-1" height=30px width=30px>
              {# <a href="{{ url_for('player_bp.display_player_info', player_tag=member_data['tag'][1:]) }}" 
                  class="text-decoration-none text-body"> #} {{ member_data['name'] }} {# </a> #}
            </td>
            {% for ClanWar in ClanWarLog['print'] %}
              {% for i in ['1', '2'] %}
                {% set attack_key = ClanWar['endTime'][:8] + '-' + i %}
                {% set attack_details = member_data[attack_key] if attack_key in member_data else none %}

                {% if attack_key in member_data %} 
                  {% if 'defenderTag' in attack_details %}
                    {% set defender = ClanWarLog['player'][attack_details['defenderTag']] %}
                    <td class="text-center text-nowrap">
                      {{ defender['mapPosition'] }}.&nbsp;
                      <img src="{{ url_for('static', filename='1_' + defender['townhallLevel']|string + '.png') }}"
                           alt="TH{{ defender['townhallLevel'] }}" class="me-1" height=30px width=30px><br/>
                      <small>
                        {% for j in range(0, attack_details['stars']) %}<i class="bi bi-star-fill text-warning"></i>{% endfor %}
                        <span class="mx-1">/</span>{{ "%.1f"|format(attack_details['destructionPercentage']) }}%
                      </small>
                    </td>
                  {% else %}<td>/</td>{% endif %}
                {% else %}<td></td>{% endif %}
              {% endfor %}
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <div class="alert alert-info text-center" role="alert">
      Clan War Log data is unavailable
    </div>
  {% endif %}
  {# dumpdata|safe #}
{% endblock %}

templates/index.html
<!doctype html>
<!--
 Copyright 2021 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<html>
<head>
  <title>Datastore and Firebase Auth Example</title>
  <script src="{{ url_for('static', filename='script.js') }}"></script>
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

  <h1>Datastore and Firebase Auth Example</h1>

  <h2>Last 10 visits</h2>
  
  {{ jsonData }}

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand text-primary" href="{{ url_for('clan_bp.clan') }}">ClashOfClans</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Clan</a>
          <ul class="dropdown-menu">
            {% set clan_list = cocparm['cocinfo_clan_list'] %}
            {% for clan_tag, clan_name in clan_list.items() %}
              <li><a class="dropdown-item" href="{{ url_for('clan_bp.get_clan_details', clan_tag=clan_tag) }}">{{ clan_name }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if ThisHTML == "clanwarlog" %}active{% endif %}" href="#">ClanWarLog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if ThisHTML == "clanwarleague" %}active{% endif %}" href="#">ClanWarLeague</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if ThisHTML == "player" %}active{% endif %}" href="#">Player</a>
        </li>
    </div>
  </div>
</nav>

templates/supertroops.html
{# ./templates/supertroops.html #}

{% extends 'base.html' %}

{% block header %}
  {% if ClanData %}
    {% set formatted_clantag = ClanData['tag'][1:] %}

    <div class="d-flex align-items-center mb-3">
      <a href="{{ url_for('clan_bp.get_clan_details', clan_tag=formatted_clantag) }}" class="text-decoration-none d-flex align-items-center">
        <img src="{{ ClanData['badgeUrls']['small'] }}" alt={{ ClanData['name'] }} class="me-3" style="max-height: 60px;">
        <h1>{% block title %}{{ ClanData['name'] }} Super Troops{% endblock %}</h1></a>
    </div>

    <div class="d-flex flex-wrap gap-2 mb-3">
      <a href="{{ url_for('clan_bp.display_currentwar', clan_tag=formatted_clantag) }}" 
        class="btn btn-secondary btn-sm{% if not ClanData['isWarLogPublic'] %} disabled{% endif %}">Current War</a>
      <a href="{{ url_for('clan_bp.display_war_log', clan_tag=formatted_clantag) }}" 
        class="btn btn-secondary btn-sm{% if not ClanData['isWarLogPublic'] %} disabled{% endif %}">War Log</a>
      <a href="{{ url_for('clan_bp.display_clan_progress', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Clan Progress</a>
      <a href="{{ url_for('clan_bp.supertroops', clan_tag=formatted_clantag) }}" class="btn btn-primary btn-sm active">Super Troops</a>
      <a href="{{ url_for('cwl_bp.display_cwl_info', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">CWL (local)</a>
      <a href="{{ url_for('clan_bp.display_clan_troops', clan_tag=formatted_clantag) }}" class="btn btn-secondary btn-sm">Troops</a>

      <a href="https://www.clashofstats.com/clans/{{ formatted_clantag }}/history/past-members" class="btn btn-outline-info btn-sm"
        target="_blank" rel="noopener noreferrer">Past Members<i class="bi bi-box-arrow-up-right ms-1"></i></a>
    </div>

  {% else %}
    <div class="alert alert-info text-center" role="alert">
        Clan data is unavailable.
    </div>

  {% endif %}
{% endblock %}

{% block content %}
  {% if ClanData %}
  {% set activeSuperTroops = ClanData['activeSuperTroops'] %}
    <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover align-middle">
        <thead>
          <tr>
            <th class="text-nowrap">Super Troop</th>
            <th class="text-nowrap">Active Members</th>
          </tr>
        </thead>
        <tbody>
          {% for troops_name, members_list in activeSuperTroops.items()  %}
          <tr>
            <td>{{ troops_name }}</td>
            <td>
            {% for member in members_list %}
              <span class="badge text-bg-secondary py-1 px-2">{{ member }}</span>
            {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endblock %}